### ISSUE TITLE
Reservation calendar not working in firefox

### ISSUE THREAD

**Issue by Northo** [MAKENTNU/web#131]
Browser: Firefox 62.0 on Linux
Reservations show up with height 0.

Possible solution: Set height of wrapper `<td class="wrapper"` to 100%

**Comment by Northo** [comment]
Arch Linux. I will provide more detailed info as soon as I get back to the computer.

**Comment by Northo** [comment]
# Environment:
OS: Arch Linux
- `uname -a`: Linux XXX 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux

Browser: Mozilla Firefox 62.0.2

# Reproduce
Open [reservation calendar.](https://makentnu.no/reservation/2018/40/3D-printer/2)

# Issue
The reservation 'blocks' shows up with no height stacked on top of each other.

As is:
![As is (no specified height of parent wrapper)](https://user-images.githubusercontent.com/7114880/46315631-423c8f00-c5ce-11e8-9e3b-6123d0ae6f6c.png)
With height of parent wrapper explicitly set to 100%:
![With height of parent wrapper specified](https://user-images.githubusercontent.com/7114880/46315630-41a3f880-c5ce-11e8-9114-5b843d4f8431.png)

Please let me know if you need anything else.

**Comment by Northo** [comment]
This is a known difference between browsers, where the CSS specs for height have been interpreted in different ways. See [this question at stackoverflow](https://stackoverflow.com/questions/5657964/css-why-doesn-t-percentage-height-work#5658062) and [this one](https://stackoverflow.com/questions/35532987/heights-rendering-differently-in-chrome-and-firefox#35537510).

**Comment by Northo** [comment]
Ok. I did not mean to imply that you did not know what you where doing. Sorry if I gave offense. Do you have any tips on what I can do to debug this?

**Comment by zootos** [comment]
No offence taken. I think the problem lies in that your Firefox installation does somehow not use the `@-moz-document url-prefix()` attribute. I do not have any clue why, however, I think the best solution may be for you to try create a new clean Firefox installation.

**Comment by kalkins** [comment]
I have the same problem, firefox 62.0.2, arch linux

**Comment by zootos** [comment]
Might be some problem with the the Firefox code base for Arch then

**Comment by kalkins** [comment]
It seems that that the use of that property has been restricted due to a bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1035091

**Comment by kalkins** [comment]
Arch is bleeding edge, so it is possible that it has been removed in our version, but that it hasn't been pushed to other distros/os yet

**Comment by kalkins** [comment]
Relevant StackOverflow answer: https://stackoverflow.com/a/48398926

**Comment by Northo** [comment]
Also reproduced on Firefox for Android 62.0.2 on Samsung Galaxy S7 edge with Android 8.0.0.

**Comment by kalkins** [comment]
`@supports (-moz-appearance:none)` seems to work, and doesn't interfere with chromium

**Comment by Northo** [comment]
Commit that fixes issue: 538a23b
