### ISSUE TITLE
Feature to search for a time slot of given length

### ISSUE THREAD

**Issue by Northo** [MAKENTNU/web#332]
It is now cumbersome to find an available time slot of a given length. It would be nice with a feature like "find available slots of length X" which searches across all machines.

**Comment by hermabe** [comment]
This is available at https://makentnu.no/en/reservation/slot/

Or did you mean something else?

**Comment by Northo** [comment]
No, that's exactly what I imagined. I see now that the link to that page is only visible when the user is logged in. I would suggest adding it also for non-authenticated users.

**Comment by Northo** [comment]
Also, hijacking my own issue here, would be nice adding a feature to put bounds on the search, in the sense of having the option to limit which days to search over, but that's just a detail.

**Comment by Northo** [comment]
Thanks for the swift reply:) Closing
