### ISSUE TITLE
Misplaced ribbon label

### ISSUE THREAD

**Issue by timmychan97** [MAKENTNU/web#386]
Here are some images showing the issue:
![image](https://user-images.githubusercontent.com/16370297/138557814-e28a0895-254e-4031-8b1e-3f902bd7a5fb.png)
![image](https://user-images.githubusercontent.com/16370297/138557869-9e18ea3c-7e78-4bfa-8fa5-96e8384274d3.png)

Actually Formatic-UI has a fix for this. You need to upgrade the library.
https://github.com/fomantic/Fomantic-UI/issues/708

Alternatively, this can be quickly (and hacky) fixed by selecting the `:after` of the ribbon, and setting `z-index` to something negative.

**Comment by ddabble** [comment]
Hm, that fix seems to have been included in version 2.7.5 of Fomantic-UI, but we already have version 2.8.7 😅🤔 Nonetheless, I created PR #387, which both upgrades Fomantic-UI to the newest version (2.8.8), and implements the fix that you suggested. Thank you for reporting this! 😊
